gate:
  search-range:
    x: 4
    y: 4
    z: 4
  blocks:
    - 85
    - 101
    - 102
    - 113
bridge:
  blocks:
    - 4
    - 5
    - 24
    - 35
    - 45
  max-size:
    width: 3
    length: 10